Repository helm/monocular, pull requests merged in 2018-12, with the labels that each got.

#569 Adding ability to customize the header about URL
  chart/monocular/templates/ui-config.yaml
  chart/monocular/values.yaml
  frontend/src/app/header-bar/header-bar.component.html
  frontend/src/app/header-bar/header-bar.component.spec.ts
  frontend/src/app/header-bar/header-bar.component.ts
  frontend/src/app/main-header/main-header.component.spec.ts
  frontend/src/app/shared/services/config.service.ts
  frontend/src/assets/js/overrides.js
Labels: size/S

#571 Filter list response with unique results
  cmd/chartsvc/handler.go
  cmd/chartsvc/handler_test.go
  cmd/chartsvc/main_test.go
Labels: size/M

#573 Updated the footer links
  frontend/src/app/footer/footer.component.html
Labels: size/XS

#572 fetch list of repos to show in ui from server
  chart/monocular/templates/ui-config.yaml
  frontend/src/app/app.module.ts
  frontend/src/app/charts/charts.component.ts
  frontend/src/app/shared/services/repos.service.ts
  frontend/src/assets/js/repos.json
Labels: size/M

#575 Footer updates
  frontend/src/app/footer/footer.component.html
  frontend/src/app/footer/footer.component.scss
  frontend/src/assets/images/logo-CNCF.png
  frontend/src/index.html
Labels: size/M

#578 Allow to use a custom CA bundle in chart-repo
  cmd/chart-repo/utils.go
  cmd/chart-repo/utils_test.go
Labels: size/M

#581 Run chart-repo as non-privileged user
  cmd/chart-repo/Dockerfile
Labels: size/XS
