Repository helm/monocular, pull requests merged in 2019-02, with the labels that each got.

#597 make repo schedule and successful Job history count configurable
  chart/monocular/Chart.yaml
  chart/monocular/README.md
  chart/monocular/templates/repo-sync-cronjobs.yaml
  chart/monocular/values.yaml
Labels: size/S

#599 Show repo name as a namespace
  frontend/src/app/chart-item/chart-item.component.html
  frontend/src/app/chart-item/chart-item.component.scss
Labels: size/M

#598 chart: Add networkPolicy
  chart/monocular/Chart.yaml
  chart/monocular/templates/chartsvc-networkpolicy.yaml
  chart/monocular/templates/prerender-networkpolicy.yaml
  chart/monocular/templates/ui-networkpolicy.yaml
  chart/monocular/values.yaml
Labels: size/M

#602 Respect $HTTP_PROXY (#601)
  cmd/chart-repo/utils.go
Labels: size/XS
