Repository helm/monocular, pull requests merged in 2019-10, with the labels that each got.

#645 Populate and serve values.schema.json if exists
  cmd/chart-repo/types.go
  cmd/chart-repo/utils.go
  cmd/chart-repo/utils_test.go
  cmd/chartsvc/handler.go
  cmd/chartsvc/handler_test.go
  cmd/chartsvc/main.go
  cmd/chartsvc/main_test.go
  cmd/chartsvc/models/chart.go
Labels: size/L

#647 [GH-646] Incorrect value name for repos in chart README
  chart/monocular/Chart.yaml
  chart/monocular/README.md
Labels: size/XS

#644 Update chart resources apiVersion
  chart/monocular/Chart.yaml
  chart/monocular/requirements.lock
  chart/monocular/requirements.yaml
  chart/monocular/templates/chartsvc-deployment.yaml
  chart/monocular/templates/prerender-deployment.yaml
  chart/monocular/templates/ui-deployment.yaml
Labels: size/S
