Repository helm/monocular, pull requests merged in 2019-03, with the labels that each got.

#606 Removing emeritus maintainers from OWNERS
  OWNERS
Labels: size/XS

#607 add andresmgot as an OWNER
  OWNERS
Labels: size/XS

#605 chartsvc: Add support for pagination
  Gopkg.lock
  cmd/chartsvc/handler.go
  cmd/chartsvc/handler_test.go
  vendor/github.com/kubeapps/common/datastore/datastore.go
  vendor/github.com/kubeapps/common/datastore/mockstore/mockstore.go
  vendor/github.com/kubeapps/common/response/response.go
Labels: size/L

#604 Added check for empty charts in chart-repo
  cmd/chart-repo/testdata/empty-repo-index.yaml
  cmd/chart-repo/utils.go
  cmd/chart-repo/utils_test.go
Labels: size/S

#611 ingress that works with ingress-nginx 0.22 and higher
  chart/monocular/Chart.yaml
  chart/monocular/templates/ingress.yaml
  chart/monocular/values.yaml
Labels: size/XS

#609 Add search endpoint
  cmd/chartsvc/handler.go
  cmd/chartsvc/main.go
Labels: size/M

#616 Check member is defined before calling match
  frontend/src/app/shared/services/charts.service.ts
Labels: size/S
