Repository helm/monocular, pull requests merged in 2019-05, with the labels that each got.

#625 Added noProxy
  chart/monocular/Chart.yaml
  chart/monocular/templates/_helpers.tpl
  chart/monocular/values.yaml
Labels: size/XS

#628 [chartsvc] Allow to return duplicated charts
  cmd/chartsvc/handler.go
  cmd/chartsvc/handler_test.go
  cmd/chartsvc/main.go
Labels: size/M

#629 Correct outdated link on details page
  frontend/src/app/chart-details/chart-details-usage/chart-details-usage.component.html
Labels: size/XS

#631 Add support for SVG icons
  cmd/chart-repo/utils.go
  cmd/chart-repo/utils_test.go
  cmd/chartsvc/handler.go
  cmd/chartsvc/handler_test.go
  cmd/chartsvc/main.go
  cmd/chartsvc/main_test.go
  cmd/chartsvc/models/chart.go
Labels: size/L
